config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "post_threads#top"
  resources :post_threads, only: [:index, :new, :create, :show] do
  	resources :post_comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :post_thread_category_relations
	has_many :categories, through: :post_thread_category_relations
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post_thread
	attachment :image
end

app/models/post_thread.rb
class PostThread < ApplicationRecord
	belongs_to :user
	has_many :post_comments
	has_many :post_thread_category_relations
	has_many :categories, through: :post_thread_category_relations
	attachment :image
end

app/models/post_thread_category_relation.rb
class PostThreadCategoryRelation < ApplicationRecord
	belongs_to :post_thread
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_threads, dependent: :destroy
  has_many :post_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action	:search
	  def after_sign_in_path_for(resource)
	    post_threads_path # ログイン後に遷移するpathを設定
	  end

	  def after_sign_up_path_for(resource)
	  	post_threads_path # サインアップ後に遷移するpathを設定
	  end

	  def after_sign_out_path_for(resource)
	    root_path # ログアウト後に遷移するpathを設定
	  end

	  def search
	  	@search = PostThread.ransack(params[:q])
	  	@post_threads = @search.result(distinct: true)
	  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		post_thread = PostThread.find(params[:post_thread_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_thread_id = post_thread.id
		comment.save
		redirect_to post_thread_path(post_thread)
	end
	private
	def post_comment_params
		params.require(:post_comment).permit(:user_id, :post_thread_id, :image, :comment)
	end
end

app/controllers/post_threads_controller.rb
class PostThreadsController < ApplicationController
	before_action :authenticate_user!
	def index
		#@post_threads = PostThread.all
	end
	def new
		@post_thread = PostThread.new
		binding.pry
		@post_thread.post_thread_category_relations.build
		@user = current_user
	end
	def create
		@post_thread = PostThread.new(post_thread_params)
		@post_thread.user_id = current_user.id
		@post_thread.save
		redirect_to post_threads_path
	end
	def show
		@post_thread = PostThread.find(params[:id])
		@post_comment =PostComment.new
		@search = PostThread.ransack(params[:q])
	  	@post_threads = @search.result(distinct: true)
	end

	private
	def post_thread_params
		params.require(:post_thread).permit(:title, :comment, :image, category_ids: [])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_threads_helper.rb
module PostThreadsHelper
end

app/views/layouts/_search.html.erb
<%= search_form_for search, url: post_threads_path do |f| %>
<%= f.search_field :title_or_comment_cont, placeholder: '検索ワードを入力', class: 'form-control mr-sm-2'%>
<%= f.submit "検索", class: 'btn btn-outline-success my-2 my-sm-0' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9323dd025d.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="wrapper">
        <nav class="navbar navbar-light bg-light">
            <div class="navbar-brand ">
                <%= link_to "chat_app",root_path %>
            </div>
            <form class="form-inline">
                <!-- ユーザーがログインしている時  -->
                <% if  user_signed_in? %>
                <ul class="nav navbar ml-auto">
                    <!-- リンクのみ -->
                    <li class="nav-item fas mr-4 text-dark">
                      <%= current_user.email %>
                    </li>
                    <li class="nav-item"><%= link_to "  スレッド一覧", post_threads_path,  class: 'fas mr-4 text-dark' %></li>
                    <li class="nav-item">
                        <%= link_to "  スレッド作成", new_post_thread_path,  class: 'fas mr-4 text-dark' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "   Logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt mr-4 text-dark" %>
                    </li>
                    <li>
                        <%= render 'layouts/search', search: @search %>
                    </li>
                </ul>
                <!-- ログインしていない時 -->
                <% else %>
                <ul class="nav navbar ml-auto">
                    <!-- リンクのみ -->
                    <li>
                        <%= link_to "   Sign-up", new_user_registration_path, class: 'fas fa-user-plus mr-4 text-dark' %>
                    </li>
                    <li>
                        <%= link_to "   Login", new_user_session_path, class: 'fas fa-sign-in-alt mr-4 text-dark' %>
                    </li>
                </ul>
                <% end %>
            </form>
        </nav>
        <div class="container-fluid mb-4">
            <%= yield %>
        </div>
        <footer class="align-center  text-center">
            <h6 class="text-center">@CopyRight hoge.inc</h6>
        </footer>
    </div>
</body>

</html>

app/views/post_threads/index.html.erb
<div class="container">
	<h1>スレッド一覧</h1>
	<div class="row">

	<table class="table table-hover">
		<thead>
			<tr>
				<th>タイトル</th>
			</tr>
		</thead>
		<% @post_threads.each do |thread| %>
		<tbody>
			<tr>
				<td><%= link_to thread.title, post_thread_path(thread.id) %><i class="float-right"><%= "コメント：#{thread.post_comments.count}" %></i></td>
			</tr>
		</tbody>
		<% end %>
	</table>
	</div>
</div>

app/views/post_threads/new.html.erb
<div class="container">
    <h1 class="mb-4">スレッド作成</h1>
    <%= form_for(@post_thread) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title, placeholder: "Title", class: "form-control mb-3" %>
    <h4>コメント</h4>
    <%= f.text_area :comment, placeholder: "Comment", class: "form-control mb-3" %>
    <h4>画像</h4>
    <%= f.attachment_field :image %>

    <h4>カテゴリー</h4>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |category| %>
    <%= category.label do %>
    <%= category.check_box %>
    <%= category.text %>
    <% end %>
    <% end %>
    <%= f.submit "作成", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/post_threads/show.html.erb
<div class="container">
    <h1>
        <%= @post_thread.title %>
    </h1>
    <p>カテゴリー
        <% @post_thread.categories.each do |category| %>
        <%= "##{category.name}" %>
        <% end %>
    </p>
    <div class="row">
        <div class="col-lg-10">
            <ul>
                <li class="list-group-item clearfix">
                    <%= @post_thread.created_at.strftime('%m月%d日 %H:%M:%S') %>
                    <i class="float-right">
                        <%= "user.id#{@post_thread.user_id}" %></i><br>
                    <%= @post_thread.comment %>
                    <i class="float-right">
                        <%= attachment_image_tag @post_thread, :image, :width => '100', :height => '100', format: "jpg" %></i>
                </li>
                <% @post_thread.post_comments.each do |comment| %>
                <li class="list-group-item  clearfix">
                    <%= comment.created_at.strftime('%m月%d日 %H:%M:%S') %>
                    <i class="float-right">
                        <%= "user.id#{comment.user.id}" %></i><br>
                    <%= comment.comment %>
                    <%= attachment_image_tag comment, :image, :width => '100', :height => '100', format: "jpg", class: "float-right" %>
                </li>
                <% end %>
            </ul>
        </div>
        <div class="col-lg-2">
            <%= form_for [@post_thread, @post_comment] do |f| %>
            <%= f.text_area :comment, class: "form-control mb-1", placeholder: "コメント" %>
            <%= f.attachment_field :image %>
            <%= f.submit "投稿", class: "btn btn-primary mt-1" %>
            <% end %>
        </div>
    </div>
</div>

app/views/post_threads/top.html.erb
<%= flash[:notice] %>
<div class="top">
	<h1>Welcom to Chat_app!!</h1>

	<%= link_to "Log in", new_user_session_path, class: "log-in col-10-md btn btn-info" %>
	<%= link_to "Sign up", new_user_registration_path, class: "sign-up col-10-md btn btn-success" %>
</div>